<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : messages.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf message : BitWasp.TrezorProto.GetAddress
 */
class GetAddress extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * address_n repeated uint32 = 1
     *
     * @var \Protobuf\Collection
     */
    protected $address_n = null;

    /**
     * coin_name optional string = 2
     *
     * @var string
     */
    protected $coin_name = null;

    /**
     * show_display optional bool = 3
     *
     * @var bool
     */
    protected $show_display = null;

    /**
     * multisig optional message = 4
     *
     * @var \BitWasp\TrezorProto\MultisigRedeemScriptType
     */
    protected $multisig = null;

    /**
     * script_type optional enum = 5
     *
     * @var \BitWasp\TrezorProto\InputScriptType
     */
    protected $script_type = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->coin_name = 'Bitcoin';
        $this->script_type = \BitWasp\TrezorProto\InputScriptType::SPENDADDRESS();

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'address_n' has a value
     *
     * @return bool
     */
    public function hasAddressNList()
    {
        return $this->address_n !== null;
    }

    /**
     * Get 'address_n' value
     *
     * @return \Protobuf\Collection
     */
    public function getAddressNList()
    {
        return $this->address_n;
    }

    /**
     * Set 'address_n' value
     *
     * @param \Protobuf\Collection $value
     */
    public function setAddressNList(\Protobuf\Collection $value = null)
    {
        $this->address_n = $value;
    }

    /**
     * Add a new element to 'address_n'
     *
     * @param int $value
     */
    public function addAddressN($value)
    {
        if ($this->address_n === null) {
            $this->address_n = new \Protobuf\ScalarCollection();
        }

        $this->address_n->add($value);
    }

    /**
     * Check if 'coin_name' has a value
     *
     * @return bool
     */
    public function hasCoinName()
    {
        return $this->coin_name !== null;
    }

    /**
     * Get 'coin_name' value
     *
     * @return string
     */
    public function getCoinName()
    {
        return $this->coin_name;
    }

    /**
     * Set 'coin_name' value
     *
     * @param string $value
     */
    public function setCoinName($value = null)
    {
        $this->coin_name = $value;
    }

    /**
     * Check if 'show_display' has a value
     *
     * @return bool
     */
    public function hasShowDisplay()
    {
        return $this->show_display !== null;
    }

    /**
     * Get 'show_display' value
     *
     * @return bool
     */
    public function getShowDisplay()
    {
        return $this->show_display;
    }

    /**
     * Set 'show_display' value
     *
     * @param bool $value
     */
    public function setShowDisplay($value = null)
    {
        $this->show_display = $value;
    }

    /**
     * Check if 'multisig' has a value
     *
     * @return bool
     */
    public function hasMultisig()
    {
        return $this->multisig !== null;
    }

    /**
     * Get 'multisig' value
     *
     * @return \BitWasp\TrezorProto\MultisigRedeemScriptType
     */
    public function getMultisig()
    {
        return $this->multisig;
    }

    /**
     * Set 'multisig' value
     *
     * @param \BitWasp\TrezorProto\MultisigRedeemScriptType $value
     */
    public function setMultisig(\BitWasp\TrezorProto\MultisigRedeemScriptType $value = null)
    {
        $this->multisig = $value;
    }

    /**
     * Check if 'script_type' has a value
     *
     * @return bool
     */
    public function hasScriptType()
    {
        return $this->script_type !== null;
    }

    /**
     * Get 'script_type' value
     *
     * @return \BitWasp\TrezorProto\InputScriptType
     */
    public function getScriptType()
    {
        return $this->script_type;
    }

    /**
     * Set 'script_type' value
     *
     * @param \BitWasp\TrezorProto\InputScriptType $value
     */
    public function setScriptType(\BitWasp\TrezorProto\InputScriptType $value = null)
    {
        $this->script_type = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'address_n' => [],
            'coin_name' => 'Bitcoin',
            'show_display' => null,
            'multisig' => null,
            'script_type' => \BitWasp\TrezorProto\InputScriptType::SPENDADDRESS()
        ], $values);

        $message->setCoinName($values['coin_name']);
        $message->setShowDisplay($values['show_display']);
        $message->setMultisig($values['multisig']);
        $message->setScriptType($values['script_type']);

        foreach ($values['address_n'] as $item) {
            $message->addAddressN($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'GetAddress',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'address_n',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'coin_name',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'default_value' => 'Bitcoin'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'show_display',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'multisig',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.BitWasp.TrezorProto.MultisigRedeemScriptType'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'script_type',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.BitWasp.TrezorProto.InputScriptType',
                    'default_value' => \BitWasp\TrezorProto\InputScriptType::SPENDADDRESS()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->address_n !== null) {
            foreach ($this->address_n as $val) {
                $writer->writeVarint($stream, 8);
                $writer->writeVarint($stream, $val);
            }
        }

        if ($this->coin_name !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->coin_name);
        }

        if ($this->show_display !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeBool($stream, $this->show_display);
        }

        if ($this->multisig !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeVarint($stream, $this->multisig->serializedSize($sizeContext));
            $this->multisig->writeTo($context);
        }

        if ($this->script_type !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeVarint($stream, $this->script_type->value());
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                if ($this->address_n === null) {
                    $this->address_n = new \Protobuf\ScalarCollection();
                }

                $this->address_n->add($reader->readVarint($stream));

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->coin_name = $reader->readString($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->show_display = $reader->readBool($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \BitWasp\TrezorProto\MultisigRedeemScriptType();

                $this->multisig = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->script_type = \BitWasp\TrezorProto\InputScriptType::valueOf($reader->readVarint($stream));

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->address_n !== null) {
            foreach ($this->address_n as $val) {
                $size += 1;
                $size += $calculator->computeVarintSize($val);
            }
        }

        if ($this->coin_name !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->coin_name);
        }

        if ($this->show_display !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->multisig !== null) {
            $innerSize = $this->multisig->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->script_type !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->script_type->value());
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->address_n = null;
        $this->coin_name = 'Bitcoin';
        $this->show_display = null;
        $this->multisig = null;
        $this->script_type = \BitWasp\TrezorProto\InputScriptType::SPENDADDRESS();
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \BitWasp\TrezorProto\GetAddress) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->address_n = ($message->address_n !== null) ? $message->address_n : $this->address_n;
        $this->coin_name = ($message->coin_name !== null) ? $message->coin_name : $this->coin_name;
        $this->show_display = ($message->show_display !== null) ? $message->show_display : $this->show_display;
        $this->multisig = ($message->multisig !== null) ? $message->multisig : $this->multisig;
        $this->script_type = ($message->script_type !== null) ? $message->script_type : $this->script_type;
    }


}

