<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : messages.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf message : BitWasp.TrezorProto.LoadDevice
 */
class LoadDevice extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * mnemonic optional string = 1
     *
     * @var string
     */
    protected $mnemonic = null;

    /**
     * node optional message = 2
     *
     * @var \BitWasp\TrezorProto\HDNodeType
     */
    protected $node = null;

    /**
     * pin optional string = 3
     *
     * @var string
     */
    protected $pin = null;

    /**
     * passphrase_protection optional bool = 4
     *
     * @var bool
     */
    protected $passphrase_protection = null;

    /**
     * language optional string = 5
     *
     * @var string
     */
    protected $language = null;

    /**
     * label optional string = 6
     *
     * @var string
     */
    protected $label = null;

    /**
     * skip_checksum optional bool = 7
     *
     * @var bool
     */
    protected $skip_checksum = null;

    /**
     * u2f_counter optional uint32 = 8
     *
     * @var int
     */
    protected $u2f_counter = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->language = 'english';

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'mnemonic' has a value
     *
     * @return bool
     */
    public function hasMnemonic()
    {
        return $this->mnemonic !== null;
    }

    /**
     * Get 'mnemonic' value
     *
     * @return string
     */
    public function getMnemonic()
    {
        return $this->mnemonic;
    }

    /**
     * Set 'mnemonic' value
     *
     * @param string $value
     */
    public function setMnemonic($value = null)
    {
        $this->mnemonic = $value;
    }

    /**
     * Check if 'node' has a value
     *
     * @return bool
     */
    public function hasNode()
    {
        return $this->node !== null;
    }

    /**
     * Get 'node' value
     *
     * @return \BitWasp\TrezorProto\HDNodeType
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     * Set 'node' value
     *
     * @param \BitWasp\TrezorProto\HDNodeType $value
     */
    public function setNode(\BitWasp\TrezorProto\HDNodeType $value = null)
    {
        $this->node = $value;
    }

    /**
     * Check if 'pin' has a value
     *
     * @return bool
     */
    public function hasPin()
    {
        return $this->pin !== null;
    }

    /**
     * Get 'pin' value
     *
     * @return string
     */
    public function getPin()
    {
        return $this->pin;
    }

    /**
     * Set 'pin' value
     *
     * @param string $value
     */
    public function setPin($value = null)
    {
        $this->pin = $value;
    }

    /**
     * Check if 'passphrase_protection' has a value
     *
     * @return bool
     */
    public function hasPassphraseProtection()
    {
        return $this->passphrase_protection !== null;
    }

    /**
     * Get 'passphrase_protection' value
     *
     * @return bool
     */
    public function getPassphraseProtection()
    {
        return $this->passphrase_protection;
    }

    /**
     * Set 'passphrase_protection' value
     *
     * @param bool $value
     */
    public function setPassphraseProtection($value = null)
    {
        $this->passphrase_protection = $value;
    }

    /**
     * Check if 'language' has a value
     *
     * @return bool
     */
    public function hasLanguage()
    {
        return $this->language !== null;
    }

    /**
     * Get 'language' value
     *
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Set 'language' value
     *
     * @param string $value
     */
    public function setLanguage($value = null)
    {
        $this->language = $value;
    }

    /**
     * Check if 'label' has a value
     *
     * @return bool
     */
    public function hasLabel()
    {
        return $this->label !== null;
    }

    /**
     * Get 'label' value
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Set 'label' value
     *
     * @param string $value
     */
    public function setLabel($value = null)
    {
        $this->label = $value;
    }

    /**
     * Check if 'skip_checksum' has a value
     *
     * @return bool
     */
    public function hasSkipChecksum()
    {
        return $this->skip_checksum !== null;
    }

    /**
     * Get 'skip_checksum' value
     *
     * @return bool
     */
    public function getSkipChecksum()
    {
        return $this->skip_checksum;
    }

    /**
     * Set 'skip_checksum' value
     *
     * @param bool $value
     */
    public function setSkipChecksum($value = null)
    {
        $this->skip_checksum = $value;
    }

    /**
     * Check if 'u2f_counter' has a value
     *
     * @return bool
     */
    public function hasU2fCounter()
    {
        return $this->u2f_counter !== null;
    }

    /**
     * Get 'u2f_counter' value
     *
     * @return int
     */
    public function getU2fCounter()
    {
        return $this->u2f_counter;
    }

    /**
     * Set 'u2f_counter' value
     *
     * @param int $value
     */
    public function setU2fCounter($value = null)
    {
        $this->u2f_counter = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'mnemonic' => null,
            'node' => null,
            'pin' => null,
            'passphrase_protection' => null,
            'language' => 'english',
            'label' => null,
            'skip_checksum' => null,
            'u2f_counter' => null
        ], $values);

        $message->setMnemonic($values['mnemonic']);
        $message->setNode($values['node']);
        $message->setPin($values['pin']);
        $message->setPassphraseProtection($values['passphrase_protection']);
        $message->setLanguage($values['language']);
        $message->setLabel($values['label']);
        $message->setSkipChecksum($values['skip_checksum']);
        $message->setU2fCounter($values['u2f_counter']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'LoadDevice',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'mnemonic',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'node',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.BitWasp.TrezorProto.HDNodeType'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'pin',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'passphrase_protection',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'language',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'default_value' => 'english'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'label',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 7,
                    'name' => 'skip_checksum',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 8,
                    'name' => 'u2f_counter',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->mnemonic !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->mnemonic);
        }

        if ($this->node !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeVarint($stream, $this->node->serializedSize($sizeContext));
            $this->node->writeTo($context);
        }

        if ($this->pin !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeString($stream, $this->pin);
        }

        if ($this->passphrase_protection !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeBool($stream, $this->passphrase_protection);
        }

        if ($this->language !== null) {
            $writer->writeVarint($stream, 42);
            $writer->writeString($stream, $this->language);
        }

        if ($this->label !== null) {
            $writer->writeVarint($stream, 50);
            $writer->writeString($stream, $this->label);
        }

        if ($this->skip_checksum !== null) {
            $writer->writeVarint($stream, 56);
            $writer->writeBool($stream, $this->skip_checksum);
        }

        if ($this->u2f_counter !== null) {
            $writer->writeVarint($stream, 64);
            $writer->writeVarint($stream, $this->u2f_counter);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->mnemonic = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \BitWasp\TrezorProto\HDNodeType();

                $this->node = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->pin = $reader->readString($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->passphrase_protection = $reader->readBool($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->language = $reader->readString($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->label = $reader->readString($stream);

                continue;
            }

            if ($tag === 7) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->skip_checksum = $reader->readBool($stream);

                continue;
            }

            if ($tag === 8) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->u2f_counter = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->mnemonic !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->mnemonic);
        }

        if ($this->node !== null) {
            $innerSize = $this->node->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->pin !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->pin);
        }

        if ($this->passphrase_protection !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->language !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->language);
        }

        if ($this->label !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->label);
        }

        if ($this->skip_checksum !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->u2f_counter !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->u2f_counter);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->mnemonic = null;
        $this->node = null;
        $this->pin = null;
        $this->passphrase_protection = null;
        $this->language = 'english';
        $this->label = null;
        $this->skip_checksum = null;
        $this->u2f_counter = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \BitWasp\TrezorProto\LoadDevice) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->mnemonic = ($message->mnemonic !== null) ? $message->mnemonic : $this->mnemonic;
        $this->node = ($message->node !== null) ? $message->node : $this->node;
        $this->pin = ($message->pin !== null) ? $message->pin : $this->pin;
        $this->passphrase_protection = ($message->passphrase_protection !== null) ? $message->passphrase_protection : $this->passphrase_protection;
        $this->language = ($message->language !== null) ? $message->language : $this->language;
        $this->label = ($message->label !== null) ? $message->label : $this->label;
        $this->skip_checksum = ($message->skip_checksum !== null) ? $message->skip_checksum : $this->skip_checksum;
        $this->u2f_counter = ($message->u2f_counter !== null) ? $message->u2f_counter : $this->u2f_counter;
    }


}

