<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : types.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf message : BitWasp.TrezorProto.MultisigRedeemScriptType
 */
class MultisigRedeemScriptType extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * pubkeys repeated message = 1
     *
     * @var \Protobuf\Collection<\BitWasp\TrezorProto\HDNodePathType>
     */
    protected $pubkeys = null;

    /**
     * signatures repeated bytes = 2
     *
     * @var \Protobuf\Collection
     */
    protected $signatures = null;

    /**
     * m optional uint32 = 3
     *
     * @var int
     */
    protected $m = null;

    /**
     * Check if 'pubkeys' has a value
     *
     * @return bool
     */
    public function hasPubkeysList()
    {
        return $this->pubkeys !== null;
    }

    /**
     * Get 'pubkeys' value
     *
     * @return \Protobuf\Collection<\BitWasp\TrezorProto\HDNodePathType>
     */
    public function getPubkeysList()
    {
        return $this->pubkeys;
    }

    /**
     * Set 'pubkeys' value
     *
     * @param \Protobuf\Collection<\BitWasp\TrezorProto\HDNodePathType> $value
     */
    public function setPubkeysList(\Protobuf\Collection $value = null)
    {
        $this->pubkeys = $value;
    }

    /**
     * Add a new element to 'pubkeys'
     *
     * @param \BitWasp\TrezorProto\HDNodePathType $value
     */
    public function addPubkeys(\BitWasp\TrezorProto\HDNodePathType $value)
    {
        if ($this->pubkeys === null) {
            $this->pubkeys = new \Protobuf\MessageCollection();
        }

        $this->pubkeys->add($value);
    }

    /**
     * Check if 'signatures' has a value
     *
     * @return bool
     */
    public function hasSignaturesList()
    {
        return $this->signatures !== null;
    }

    /**
     * Get 'signatures' value
     *
     * @return \Protobuf\Collection
     */
    public function getSignaturesList()
    {
        return $this->signatures;
    }

    /**
     * Set 'signatures' value
     *
     * @param \Protobuf\Collection $value
     */
    public function setSignaturesList(\Protobuf\Collection $value = null)
    {
        $this->signatures = $value;
    }

    /**
     * Add a new element to 'signatures'
     *
     * @param \Protobuf\Stream $value
     */
    public function addSignatures($value)
    {
        if ($this->signatures === null) {
            $this->signatures = new \Protobuf\StreamCollection();
        }

        $this->signatures->add(\Protobuf\Stream::wrap($value));
    }

    /**
     * Check if 'm' has a value
     *
     * @return bool
     */
    public function hasM()
    {
        return $this->m !== null;
    }

    /**
     * Get 'm' value
     *
     * @return int
     */
    public function getM()
    {
        return $this->m;
    }

    /**
     * Set 'm' value
     *
     * @param int $value
     */
    public function setM($value = null)
    {
        $this->m = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'pubkeys' => [],
            'signatures' => [],
            'm' => null
        ], $values);

        $message->setM($values['m']);

        foreach ($values['pubkeys'] as $item) {
            $message->addPubkeys($item);
        }

        foreach ($values['signatures'] as $item) {
            $message->addSignatures($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'MultisigRedeemScriptType',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'pubkeys',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.BitWasp.TrezorProto.HDNodePathType'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'signatures',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'm',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->pubkeys !== null) {
            foreach ($this->pubkeys as $val) {
                $writer->writeVarint($stream, 10);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->signatures !== null) {
            foreach ($this->signatures as $val) {
                $writer->writeVarint($stream, 18);
                $writer->writeByteStream($stream, $val);
            }
        }

        if ($this->m !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->m);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \BitWasp\TrezorProto\HDNodePathType();

                if ($this->pubkeys === null) {
                    $this->pubkeys = new \Protobuf\MessageCollection();
                }

                $this->pubkeys->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                if ($this->signatures === null) {
                    $this->signatures = new \Protobuf\StreamCollection();
                }

                $this->signatures->add($reader->readByteStream($stream));

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->m = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->pubkeys !== null) {
            foreach ($this->pubkeys as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->signatures !== null) {
            foreach ($this->signatures as $val) {
                $size += 1;
                $size += $calculator->computeByteStreamSize($val);
            }
        }

        if ($this->m !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->m);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->pubkeys = null;
        $this->signatures = null;
        $this->m = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \BitWasp\TrezorProto\MultisigRedeemScriptType) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->pubkeys = ($message->pubkeys !== null) ? $message->pubkeys : $this->pubkeys;
        $this->signatures = ($message->signatures !== null) ? $message->signatures : $this->signatures;
        $this->m = ($message->m !== null) ? $message->m : $this->m;
    }


}

