<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : types.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf message : BitWasp.TrezorProto.NEMMosaicCreation
 */
class NEMMosaicCreation extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * definition optional message = 1
     *
     * @var \BitWasp\TrezorProto\NEMMosaicDefinition
     */
    protected $definition = null;

    /**
     * sink optional string = 2
     *
     * @var string
     */
    protected $sink = null;

    /**
     * fee optional uint64 = 3
     *
     * @var int
     */
    protected $fee = null;

    /**
     * Check if 'definition' has a value
     *
     * @return bool
     */
    public function hasDefinition()
    {
        return $this->definition !== null;
    }

    /**
     * Get 'definition' value
     *
     * @return \BitWasp\TrezorProto\NEMMosaicDefinition
     */
    public function getDefinition()
    {
        return $this->definition;
    }

    /**
     * Set 'definition' value
     *
     * @param \BitWasp\TrezorProto\NEMMosaicDefinition $value
     */
    public function setDefinition(\BitWasp\TrezorProto\NEMMosaicDefinition $value = null)
    {
        $this->definition = $value;
    }

    /**
     * Check if 'sink' has a value
     *
     * @return bool
     */
    public function hasSink()
    {
        return $this->sink !== null;
    }

    /**
     * Get 'sink' value
     *
     * @return string
     */
    public function getSink()
    {
        return $this->sink;
    }

    /**
     * Set 'sink' value
     *
     * @param string $value
     */
    public function setSink($value = null)
    {
        $this->sink = $value;
    }

    /**
     * Check if 'fee' has a value
     *
     * @return bool
     */
    public function hasFee()
    {
        return $this->fee !== null;
    }

    /**
     * Get 'fee' value
     *
     * @return int
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Set 'fee' value
     *
     * @param int $value
     */
    public function setFee($value = null)
    {
        $this->fee = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'definition' => null,
            'sink' => null,
            'fee' => null
        ], $values);

        $message->setDefinition($values['definition']);
        $message->setSink($values['sink']);
        $message->setFee($values['fee']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'NEMMosaicCreation',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'definition',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.BitWasp.TrezorProto.NEMMosaicDefinition'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'sink',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'fee',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->definition !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeVarint($stream, $this->definition->serializedSize($sizeContext));
            $this->definition->writeTo($context);
        }

        if ($this->sink !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->sink);
        }

        if ($this->fee !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->fee);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \BitWasp\TrezorProto\NEMMosaicDefinition();

                $this->definition = $innerMessage;

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->sink = $reader->readString($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->fee = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->definition !== null) {
            $innerSize = $this->definition->serializedSize($context);

            $size += 1;
            $size += $innerSize;
            $size += $calculator->computeVarintSize($innerSize);
        }

        if ($this->sink !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->sink);
        }

        if ($this->fee !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->fee);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->definition = null;
        $this->sink = null;
        $this->fee = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \BitWasp\TrezorProto\NEMMosaicCreation) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->definition = ($message->definition !== null) ? $message->definition : $this->definition;
        $this->sink = ($message->sink !== null) ? $message->sink : $this->sink;
        $this->fee = ($message->fee !== null) ? $message->fee : $this->fee;
    }


}

