<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : types.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf message : BitWasp.TrezorProto.NEMProvisionNamespace
 */
class NEMProvisionNamespace extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * namespace optional string = 1
     *
     * @var string
     */
    protected $namespace = null;

    /**
     * parent optional string = 2
     *
     * @var string
     */
    protected $parent = null;

    /**
     * sink optional string = 3
     *
     * @var string
     */
    protected $sink = null;

    /**
     * fee optional uint64 = 4
     *
     * @var int
     */
    protected $fee = null;

    /**
     * Check if 'namespace' has a value
     *
     * @return bool
     */
    public function hasNamespace()
    {
        return $this->namespace !== null;
    }

    /**
     * Get 'namespace' value
     *
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Set 'namespace' value
     *
     * @param string $value
     */
    public function setNamespace($value = null)
    {
        $this->namespace = $value;
    }

    /**
     * Check if 'parent' has a value
     *
     * @return bool
     */
    public function hasParent()
    {
        return $this->parent !== null;
    }

    /**
     * Get 'parent' value
     *
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Set 'parent' value
     *
     * @param string $value
     */
    public function setParent($value = null)
    {
        $this->parent = $value;
    }

    /**
     * Check if 'sink' has a value
     *
     * @return bool
     */
    public function hasSink()
    {
        return $this->sink !== null;
    }

    /**
     * Get 'sink' value
     *
     * @return string
     */
    public function getSink()
    {
        return $this->sink;
    }

    /**
     * Set 'sink' value
     *
     * @param string $value
     */
    public function setSink($value = null)
    {
        $this->sink = $value;
    }

    /**
     * Check if 'fee' has a value
     *
     * @return bool
     */
    public function hasFee()
    {
        return $this->fee !== null;
    }

    /**
     * Get 'fee' value
     *
     * @return int
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Set 'fee' value
     *
     * @param int $value
     */
    public function setFee($value = null)
    {
        $this->fee = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'namespace' => null,
            'parent' => null,
            'sink' => null,
            'fee' => null
        ], $values);

        $message->setNamespace($values['namespace']);
        $message->setParent($values['parent']);
        $message->setSink($values['sink']);
        $message->setFee($values['fee']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'NEMProvisionNamespace',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'namespace',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'parent',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'sink',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'fee',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->namespace !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeString($stream, $this->namespace);
        }

        if ($this->parent !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->parent);
        }

        if ($this->sink !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeString($stream, $this->sink);
        }

        if ($this->fee !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->fee);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->namespace = $reader->readString($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->parent = $reader->readString($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->sink = $reader->readString($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->fee = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->namespace !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->namespace);
        }

        if ($this->parent !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->parent);
        }

        if ($this->sink !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->sink);
        }

        if ($this->fee !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->fee);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->namespace = null;
        $this->parent = null;
        $this->sink = null;
        $this->fee = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \BitWasp\TrezorProto\NEMProvisionNamespace) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->namespace = ($message->namespace !== null) ? $message->namespace : $this->namespace;
        $this->parent = ($message->parent !== null) ? $message->parent : $this->parent;
        $this->sink = ($message->sink !== null) ? $message->sink : $this->sink;
        $this->fee = ($message->fee !== null) ? $message->fee : $this->fee;
    }


}

