<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : types.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf enum : BitWasp.TrezorProto.PinMatrixRequestType
 */
class PinMatrixRequestType extends \Protobuf\Enum
{

    /**
     * PinMatrixRequestType_Current = 1
     */
    const PinMatrixRequestType_Current_VALUE = 1;

    /**
     * PinMatrixRequestType_NewFirst = 2
     */
    const PinMatrixRequestType_NewFirst_VALUE = 2;

    /**
     * PinMatrixRequestType_NewSecond = 3
     */
    const PinMatrixRequestType_NewSecond_VALUE = 3;

    /**
     * @var \BitWasp\TrezorProto\PinMatrixRequestType
     */
    protected static $PinMatrixRequestType_Current = null;

    /**
     * @var \BitWasp\TrezorProto\PinMatrixRequestType
     */
    protected static $PinMatrixRequestType_NewFirst = null;

    /**
     * @var \BitWasp\TrezorProto\PinMatrixRequestType
     */
    protected static $PinMatrixRequestType_NewSecond = null;

    /**
     * @return \BitWasp\TrezorProto\PinMatrixRequestType
     */
    public static function PinMatrixRequestType_Current()
    {
        if (self::$PinMatrixRequestType_Current !== null) {
            return self::$PinMatrixRequestType_Current;
        }

        return self::$PinMatrixRequestType_Current = new self('PinMatrixRequestType_Current', self::PinMatrixRequestType_Current_VALUE);
    }

    /**
     * @return \BitWasp\TrezorProto\PinMatrixRequestType
     */
    public static function PinMatrixRequestType_NewFirst()
    {
        if (self::$PinMatrixRequestType_NewFirst !== null) {
            return self::$PinMatrixRequestType_NewFirst;
        }

        return self::$PinMatrixRequestType_NewFirst = new self('PinMatrixRequestType_NewFirst', self::PinMatrixRequestType_NewFirst_VALUE);
    }

    /**
     * @return \BitWasp\TrezorProto\PinMatrixRequestType
     */
    public static function PinMatrixRequestType_NewSecond()
    {
        if (self::$PinMatrixRequestType_NewSecond !== null) {
            return self::$PinMatrixRequestType_NewSecond;
        }

        return self::$PinMatrixRequestType_NewSecond = new self('PinMatrixRequestType_NewSecond', self::PinMatrixRequestType_NewSecond_VALUE);
    }

    /**
     * @param int $value
     * @return \BitWasp\TrezorProto\PinMatrixRequestType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 1: return self::PinMatrixRequestType_Current();
            case 2: return self::PinMatrixRequestType_NewFirst();
            case 3: return self::PinMatrixRequestType_NewSecond();
            default: return null;
        }
    }


}

