<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : messages.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf message : BitWasp.TrezorProto.RecoveryDevice
 */
class RecoveryDevice extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * word_count optional uint32 = 1
     *
     * @var int
     */
    protected $word_count = null;

    /**
     * passphrase_protection optional bool = 2
     *
     * @var bool
     */
    protected $passphrase_protection = null;

    /**
     * pin_protection optional bool = 3
     *
     * @var bool
     */
    protected $pin_protection = null;

    /**
     * language optional string = 4
     *
     * @var string
     */
    protected $language = null;

    /**
     * label optional string = 5
     *
     * @var string
     */
    protected $label = null;

    /**
     * enforce_wordlist optional bool = 6
     *
     * @var bool
     */
    protected $enforce_wordlist = null;

    /**
     * type optional uint32 = 8
     *
     * @var int
     */
    protected $type = null;

    /**
     * u2f_counter optional uint32 = 9
     *
     * @var int
     */
    protected $u2f_counter = null;

    /**
     * dry_run optional bool = 10
     *
     * @var bool
     */
    protected $dry_run = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->language = 'english';

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'word_count' has a value
     *
     * @return bool
     */
    public function hasWordCount()
    {
        return $this->word_count !== null;
    }

    /**
     * Get 'word_count' value
     *
     * @return int
     */
    public function getWordCount()
    {
        return $this->word_count;
    }

    /**
     * Set 'word_count' value
     *
     * @param int $value
     */
    public function setWordCount($value = null)
    {
        $this->word_count = $value;
    }

    /**
     * Check if 'passphrase_protection' has a value
     *
     * @return bool
     */
    public function hasPassphraseProtection()
    {
        return $this->passphrase_protection !== null;
    }

    /**
     * Get 'passphrase_protection' value
     *
     * @return bool
     */
    public function getPassphraseProtection()
    {
        return $this->passphrase_protection;
    }

    /**
     * Set 'passphrase_protection' value
     *
     * @param bool $value
     */
    public function setPassphraseProtection($value = null)
    {
        $this->passphrase_protection = $value;
    }

    /**
     * Check if 'pin_protection' has a value
     *
     * @return bool
     */
    public function hasPinProtection()
    {
        return $this->pin_protection !== null;
    }

    /**
     * Get 'pin_protection' value
     *
     * @return bool
     */
    public function getPinProtection()
    {
        return $this->pin_protection;
    }

    /**
     * Set 'pin_protection' value
     *
     * @param bool $value
     */
    public function setPinProtection($value = null)
    {
        $this->pin_protection = $value;
    }

    /**
     * Check if 'language' has a value
     *
     * @return bool
     */
    public function hasLanguage()
    {
        return $this->language !== null;
    }

    /**
     * Get 'language' value
     *
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Set 'language' value
     *
     * @param string $value
     */
    public function setLanguage($value = null)
    {
        $this->language = $value;
    }

    /**
     * Check if 'label' has a value
     *
     * @return bool
     */
    public function hasLabel()
    {
        return $this->label !== null;
    }

    /**
     * Get 'label' value
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Set 'label' value
     *
     * @param string $value
     */
    public function setLabel($value = null)
    {
        $this->label = $value;
    }

    /**
     * Check if 'enforce_wordlist' has a value
     *
     * @return bool
     */
    public function hasEnforceWordlist()
    {
        return $this->enforce_wordlist !== null;
    }

    /**
     * Get 'enforce_wordlist' value
     *
     * @return bool
     */
    public function getEnforceWordlist()
    {
        return $this->enforce_wordlist;
    }

    /**
     * Set 'enforce_wordlist' value
     *
     * @param bool $value
     */
    public function setEnforceWordlist($value = null)
    {
        $this->enforce_wordlist = $value;
    }

    /**
     * Check if 'type' has a value
     *
     * @return bool
     */
    public function hasType()
    {
        return $this->type !== null;
    }

    /**
     * Get 'type' value
     *
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set 'type' value
     *
     * @param int $value
     */
    public function setType($value = null)
    {
        $this->type = $value;
    }

    /**
     * Check if 'u2f_counter' has a value
     *
     * @return bool
     */
    public function hasU2fCounter()
    {
        return $this->u2f_counter !== null;
    }

    /**
     * Get 'u2f_counter' value
     *
     * @return int
     */
    public function getU2fCounter()
    {
        return $this->u2f_counter;
    }

    /**
     * Set 'u2f_counter' value
     *
     * @param int $value
     */
    public function setU2fCounter($value = null)
    {
        $this->u2f_counter = $value;
    }

    /**
     * Check if 'dry_run' has a value
     *
     * @return bool
     */
    public function hasDryRun()
    {
        return $this->dry_run !== null;
    }

    /**
     * Get 'dry_run' value
     *
     * @return bool
     */
    public function getDryRun()
    {
        return $this->dry_run;
    }

    /**
     * Set 'dry_run' value
     *
     * @param bool $value
     */
    public function setDryRun($value = null)
    {
        $this->dry_run = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'word_count' => null,
            'passphrase_protection' => null,
            'pin_protection' => null,
            'language' => 'english',
            'label' => null,
            'enforce_wordlist' => null,
            'type' => null,
            'u2f_counter' => null,
            'dry_run' => null
        ], $values);

        $message->setWordCount($values['word_count']);
        $message->setPassphraseProtection($values['passphrase_protection']);
        $message->setPinProtection($values['pin_protection']);
        $message->setLanguage($values['language']);
        $message->setLabel($values['label']);
        $message->setEnforceWordlist($values['enforce_wordlist']);
        $message->setType($values['type']);
        $message->setU2fCounter($values['u2f_counter']);
        $message->setDryRun($values['dry_run']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'RecoveryDevice',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'word_count',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'passphrase_protection',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'pin_protection',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'language',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'default_value' => 'english'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'label',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'enforce_wordlist',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 8,
                    'name' => 'type',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 9,
                    'name' => 'u2f_counter',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 10,
                    'name' => 'dry_run',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->word_count !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->word_count);
        }

        if ($this->passphrase_protection !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeBool($stream, $this->passphrase_protection);
        }

        if ($this->pin_protection !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeBool($stream, $this->pin_protection);
        }

        if ($this->language !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeString($stream, $this->language);
        }

        if ($this->label !== null) {
            $writer->writeVarint($stream, 42);
            $writer->writeString($stream, $this->label);
        }

        if ($this->enforce_wordlist !== null) {
            $writer->writeVarint($stream, 48);
            $writer->writeBool($stream, $this->enforce_wordlist);
        }

        if ($this->type !== null) {
            $writer->writeVarint($stream, 64);
            $writer->writeVarint($stream, $this->type);
        }

        if ($this->u2f_counter !== null) {
            $writer->writeVarint($stream, 72);
            $writer->writeVarint($stream, $this->u2f_counter);
        }

        if ($this->dry_run !== null) {
            $writer->writeVarint($stream, 80);
            $writer->writeBool($stream, $this->dry_run);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->word_count = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->passphrase_protection = $reader->readBool($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->pin_protection = $reader->readBool($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->language = $reader->readString($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->label = $reader->readString($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->enforce_wordlist = $reader->readBool($stream);

                continue;
            }

            if ($tag === 8) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->type = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 9) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->u2f_counter = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 10) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->dry_run = $reader->readBool($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->word_count !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->word_count);
        }

        if ($this->passphrase_protection !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->pin_protection !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->language !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->language);
        }

        if ($this->label !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->label);
        }

        if ($this->enforce_wordlist !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->type !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->type);
        }

        if ($this->u2f_counter !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->u2f_counter);
        }

        if ($this->dry_run !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->word_count = null;
        $this->passphrase_protection = null;
        $this->pin_protection = null;
        $this->language = 'english';
        $this->label = null;
        $this->enforce_wordlist = null;
        $this->type = null;
        $this->u2f_counter = null;
        $this->dry_run = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \BitWasp\TrezorProto\RecoveryDevice) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->word_count = ($message->word_count !== null) ? $message->word_count : $this->word_count;
        $this->passphrase_protection = ($message->passphrase_protection !== null) ? $message->passphrase_protection : $this->passphrase_protection;
        $this->pin_protection = ($message->pin_protection !== null) ? $message->pin_protection : $this->pin_protection;
        $this->language = ($message->language !== null) ? $message->language : $this->language;
        $this->label = ($message->label !== null) ? $message->label : $this->label;
        $this->enforce_wordlist = ($message->enforce_wordlist !== null) ? $message->enforce_wordlist : $this->enforce_wordlist;
        $this->type = ($message->type !== null) ? $message->type : $this->type;
        $this->u2f_counter = ($message->u2f_counter !== null) ? $message->u2f_counter : $this->u2f_counter;
        $this->dry_run = ($message->dry_run !== null) ? $message->dry_run : $this->dry_run;
    }


}

