<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : types.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf enum : BitWasp.TrezorProto.RequestType
 */
class RequestType extends \Protobuf\Enum
{

    /**
     * TXINPUT = 0
     */
    const TXINPUT_VALUE = 0;

    /**
     * TXOUTPUT = 1
     */
    const TXOUTPUT_VALUE = 1;

    /**
     * TXMETA = 2
     */
    const TXMETA_VALUE = 2;

    /**
     * TXFINISHED = 3
     */
    const TXFINISHED_VALUE = 3;

    /**
     * TXEXTRADATA = 4
     */
    const TXEXTRADATA_VALUE = 4;

    /**
     * @var \BitWasp\TrezorProto\RequestType
     */
    protected static $TXINPUT = null;

    /**
     * @var \BitWasp\TrezorProto\RequestType
     */
    protected static $TXOUTPUT = null;

    /**
     * @var \BitWasp\TrezorProto\RequestType
     */
    protected static $TXMETA = null;

    /**
     * @var \BitWasp\TrezorProto\RequestType
     */
    protected static $TXFINISHED = null;

    /**
     * @var \BitWasp\TrezorProto\RequestType
     */
    protected static $TXEXTRADATA = null;

    /**
     * @return \BitWasp\TrezorProto\RequestType
     */
    public static function TXINPUT()
    {
        if (self::$TXINPUT !== null) {
            return self::$TXINPUT;
        }

        return self::$TXINPUT = new self('TXINPUT', self::TXINPUT_VALUE);
    }

    /**
     * @return \BitWasp\TrezorProto\RequestType
     */
    public static function TXOUTPUT()
    {
        if (self::$TXOUTPUT !== null) {
            return self::$TXOUTPUT;
        }

        return self::$TXOUTPUT = new self('TXOUTPUT', self::TXOUTPUT_VALUE);
    }

    /**
     * @return \BitWasp\TrezorProto\RequestType
     */
    public static function TXMETA()
    {
        if (self::$TXMETA !== null) {
            return self::$TXMETA;
        }

        return self::$TXMETA = new self('TXMETA', self::TXMETA_VALUE);
    }

    /**
     * @return \BitWasp\TrezorProto\RequestType
     */
    public static function TXFINISHED()
    {
        if (self::$TXFINISHED !== null) {
            return self::$TXFINISHED;
        }

        return self::$TXFINISHED = new self('TXFINISHED', self::TXFINISHED_VALUE);
    }

    /**
     * @return \BitWasp\TrezorProto\RequestType
     */
    public static function TXEXTRADATA()
    {
        if (self::$TXEXTRADATA !== null) {
            return self::$TXEXTRADATA;
        }

        return self::$TXEXTRADATA = new self('TXEXTRADATA', self::TXEXTRADATA_VALUE);
    }

    /**
     * @param int $value
     * @return \BitWasp\TrezorProto\RequestType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::TXINPUT();
            case 1: return self::TXOUTPUT();
            case 2: return self::TXMETA();
            case 3: return self::TXFINISHED();
            case 4: return self::TXEXTRADATA();
            default: return null;
        }
    }


}

