<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : messages.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf message : BitWasp.TrezorProto.SignTx
 */
class SignTx extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * outputs_count required uint32 = 1
     *
     * @var int
     */
    protected $outputs_count = null;

    /**
     * inputs_count required uint32 = 2
     *
     * @var int
     */
    protected $inputs_count = null;

    /**
     * coin_name optional string = 3
     *
     * @var string
     */
    protected $coin_name = null;

    /**
     * version optional uint32 = 4
     *
     * @var int
     */
    protected $version = null;

    /**
     * lock_time optional uint32 = 5
     *
     * @var int
     */
    protected $lock_time = null;

    /**
     * decred_expiry optional uint32 = 6
     *
     * @var int
     */
    protected $decred_expiry = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->coin_name = 'Bitcoin';
        $this->version = '1';
        $this->lock_time = '0';

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'outputs_count' has a value
     *
     * @return bool
     */
    public function hasOutputsCount()
    {
        return $this->outputs_count !== null;
    }

    /**
     * Get 'outputs_count' value
     *
     * @return int
     */
    public function getOutputsCount()
    {
        return $this->outputs_count;
    }

    /**
     * Set 'outputs_count' value
     *
     * @param int $value
     */
    public function setOutputsCount($value)
    {
        $this->outputs_count = $value;
    }

    /**
     * Check if 'inputs_count' has a value
     *
     * @return bool
     */
    public function hasInputsCount()
    {
        return $this->inputs_count !== null;
    }

    /**
     * Get 'inputs_count' value
     *
     * @return int
     */
    public function getInputsCount()
    {
        return $this->inputs_count;
    }

    /**
     * Set 'inputs_count' value
     *
     * @param int $value
     */
    public function setInputsCount($value)
    {
        $this->inputs_count = $value;
    }

    /**
     * Check if 'coin_name' has a value
     *
     * @return bool
     */
    public function hasCoinName()
    {
        return $this->coin_name !== null;
    }

    /**
     * Get 'coin_name' value
     *
     * @return string
     */
    public function getCoinName()
    {
        return $this->coin_name;
    }

    /**
     * Set 'coin_name' value
     *
     * @param string $value
     */
    public function setCoinName($value = null)
    {
        $this->coin_name = $value;
    }

    /**
     * Check if 'version' has a value
     *
     * @return bool
     */
    public function hasVersion()
    {
        return $this->version !== null;
    }

    /**
     * Get 'version' value
     *
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Set 'version' value
     *
     * @param int $value
     */
    public function setVersion($value = null)
    {
        $this->version = $value;
    }

    /**
     * Check if 'lock_time' has a value
     *
     * @return bool
     */
    public function hasLockTime()
    {
        return $this->lock_time !== null;
    }

    /**
     * Get 'lock_time' value
     *
     * @return int
     */
    public function getLockTime()
    {
        return $this->lock_time;
    }

    /**
     * Set 'lock_time' value
     *
     * @param int $value
     */
    public function setLockTime($value = null)
    {
        $this->lock_time = $value;
    }

    /**
     * Check if 'decred_expiry' has a value
     *
     * @return bool
     */
    public function hasDecredExpiry()
    {
        return $this->decred_expiry !== null;
    }

    /**
     * Get 'decred_expiry' value
     *
     * @return int
     */
    public function getDecredExpiry()
    {
        return $this->decred_expiry;
    }

    /**
     * Set 'decred_expiry' value
     *
     * @param int $value
     */
    public function setDecredExpiry($value = null)
    {
        $this->decred_expiry = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['outputs_count'])) {
            throw new \InvalidArgumentException('Field "outputs_count" (tag 1) is required but has no value.');
        }

        if ( ! isset($values['inputs_count'])) {
            throw new \InvalidArgumentException('Field "inputs_count" (tag 2) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'coin_name' => 'Bitcoin',
            'version' => '1',
            'lock_time' => '0',
            'decred_expiry' => null
        ], $values);

        $message->setOutputsCount($values['outputs_count']);
        $message->setInputsCount($values['inputs_count']);
        $message->setCoinName($values['coin_name']);
        $message->setVersion($values['version']);
        $message->setLockTime($values['lock_time']);
        $message->setDecredExpiry($values['decred_expiry']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'SignTx',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'outputs_count',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'inputs_count',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'coin_name',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'default_value' => 'Bitcoin'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'version',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'default_value' => '1'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'lock_time',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'default_value' => '0'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'decred_expiry',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->outputs_count === null) {
            throw new \UnexpectedValueException('Field "\\BitWasp\\TrezorProto\\SignTx#outputs_count" (tag 1) is required but has no value.');
        }

        if ($this->inputs_count === null) {
            throw new \UnexpectedValueException('Field "\\BitWasp\\TrezorProto\\SignTx#inputs_count" (tag 2) is required but has no value.');
        }

        if ($this->outputs_count !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->outputs_count);
        }

        if ($this->inputs_count !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->inputs_count);
        }

        if ($this->coin_name !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeString($stream, $this->coin_name);
        }

        if ($this->version !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->version);
        }

        if ($this->lock_time !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeVarint($stream, $this->lock_time);
        }

        if ($this->decred_expiry !== null) {
            $writer->writeVarint($stream, 48);
            $writer->writeVarint($stream, $this->decred_expiry);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->outputs_count = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->inputs_count = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->coin_name = $reader->readString($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->version = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->lock_time = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->decred_expiry = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->outputs_count !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->outputs_count);
        }

        if ($this->inputs_count !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->inputs_count);
        }

        if ($this->coin_name !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->coin_name);
        }

        if ($this->version !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->version);
        }

        if ($this->lock_time !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->lock_time);
        }

        if ($this->decred_expiry !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->decred_expiry);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->outputs_count = null;
        $this->inputs_count = null;
        $this->coin_name = 'Bitcoin';
        $this->version = '1';
        $this->lock_time = '0';
        $this->decred_expiry = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \BitWasp\TrezorProto\SignTx) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->outputs_count = ($message->outputs_count !== null) ? $message->outputs_count : $this->outputs_count;
        $this->inputs_count = ($message->inputs_count !== null) ? $message->inputs_count : $this->inputs_count;
        $this->coin_name = ($message->coin_name !== null) ? $message->coin_name : $this->coin_name;
        $this->version = ($message->version !== null) ? $message->version : $this->version;
        $this->lock_time = ($message->lock_time !== null) ? $message->lock_time : $this->lock_time;
        $this->decred_expiry = ($message->decred_expiry !== null) ? $message->decred_expiry : $this->decred_expiry;
    }


}

