<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : types.proto
 */


namespace BitWasp\TrezorProto;

/**
 * Protobuf enum : BitWasp.TrezorProto.WordRequestType
 */
class WordRequestType extends \Protobuf\Enum
{

    /**
     * WordRequestType_Plain = 0
     */
    const WordRequestType_Plain_VALUE = 0;

    /**
     * WordRequestType_Matrix9 = 1
     */
    const WordRequestType_Matrix9_VALUE = 1;

    /**
     * WordRequestType_Matrix6 = 2
     */
    const WordRequestType_Matrix6_VALUE = 2;

    /**
     * @var \BitWasp\TrezorProto\WordRequestType
     */
    protected static $WordRequestType_Plain = null;

    /**
     * @var \BitWasp\TrezorProto\WordRequestType
     */
    protected static $WordRequestType_Matrix9 = null;

    /**
     * @var \BitWasp\TrezorProto\WordRequestType
     */
    protected static $WordRequestType_Matrix6 = null;

    /**
     * @return \BitWasp\TrezorProto\WordRequestType
     */
    public static function WordRequestType_Plain()
    {
        if (self::$WordRequestType_Plain !== null) {
            return self::$WordRequestType_Plain;
        }

        return self::$WordRequestType_Plain = new self('WordRequestType_Plain', self::WordRequestType_Plain_VALUE);
    }

    /**
     * @return \BitWasp\TrezorProto\WordRequestType
     */
    public static function WordRequestType_Matrix9()
    {
        if (self::$WordRequestType_Matrix9 !== null) {
            return self::$WordRequestType_Matrix9;
        }

        return self::$WordRequestType_Matrix9 = new self('WordRequestType_Matrix9', self::WordRequestType_Matrix9_VALUE);
    }

    /**
     * @return \BitWasp\TrezorProto\WordRequestType
     */
    public static function WordRequestType_Matrix6()
    {
        if (self::$WordRequestType_Matrix6 !== null) {
            return self::$WordRequestType_Matrix6;
        }

        return self::$WordRequestType_Matrix6 = new self('WordRequestType_Matrix6', self::WordRequestType_Matrix6_VALUE);
    }

    /**
     * @param int $value
     * @return \BitWasp\TrezorProto\WordRequestType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::WordRequestType_Plain();
            case 1: return self::WordRequestType_Matrix9();
            case 2: return self::WordRequestType_Matrix6();
            default: return null;
        }
    }


}

